{ ... }:
{
  femboy.modules.packages =
    { pkgs, ... }:
    let
      catppuccin-icons = pkgs.callPackage ../../pkgs/catppuccin-icons.nix { };
    in
    {
      environment.systemPackages = with pkgs; [
        vim
        wget
        git
        gcc
        gnumake
        ghostty
        vscode
        nodejs
        brave
        fastfetch
        fzf
        fuzzel
        mako
        disfetch
        kitty
        yazi
        thunar
        microfetch
        spotify
        spotify-tray
        zathura
        krabby
        fish
        atuin
        any-nix-shell
        nix-your-shell
        lazygit
        tmux
        zellij
        nitch
        nix-melt
        timeshift
        emacs
        go
        g-ls
        gh
        z-lua
        hicolor-icon-theme
        adwaita-icon-theme
        kdePackages.breeze-icons
        vesktop
        pciutils
        brightnessctl
        starship
        clang-tools
        python315
        rust-analyzer
        cargo
        rustc
        rustfmt
        clippy
        firefox
        gsettings-desktop-schemas
        glib
        bun
        dconf
        zed-editor
        catppuccin-icons
        vivaldi
        obsidian
        themechanger
        ghc
        cabal-install
        haskell-language-server
        jetbrains.clion
        reaper
        pipewire.jack
        xournalpp
        bat
        fd
        ripgrep
        zoxide
        carapace
        eza
        awww
        wl-clipboard
        grim
        slurp
        playerctl
        whitesur-gtk-theme
        whitesur-cursors
        qt6Packages.qt6ct
        libsForQt5.qt5ct
        xsettingsd
      ];
    };
}
