Gdk/UnscaledDPI 98304
Gdk/WindowScalingFactor 1
Gtk/EnableAnimations 1
Gtk/DecorationLayout "icon:minimize,maximize,close"
Net/ThemeName ""
Xft/Antialias 1
Xft/Hinting 0
Xft/HintStyle "hintnone"
Xft/Lcdfilter "lcdnone"
Xft/RGBA "none"
Gtk/PrimaryButtonWarpsSlider 1
Gtk/ToolbarStyle 3
Gtk/MenuImages 1
Gtk/ButtonImages 1
Net/CursorBlinkTime 1000
Net/CursorBlink 1
Gtk/CursorThemeSize 28
Gtk/CursorThemeName "WhiteSur-cursors"
Net/SoundThemeName "ocean"
Net/IconThemeName "WhiteSur"
Gtk/FontName "Inter 10"
